### ISSUE TITLE
Amx Request 

### ISSUE THREAD

**Issue by chuksthemodder** [WoutProvost/FCNPC-Boss#23]
Sir since am unable to compile please I need the amx file thats the only thing holding me back please sir it shows that most things are not defined when I tried to compile
Please sir just the amx that's all am asking for

**Comment by WoutProvost** [comment]
Have you even tried looking at the zips in the releases?
https://github.com/WoutProvost/FCNPC-AI/releases

**Comment by chuksthemodder** [comment]
Sir I went through it and saw some pwn files (2) inc file(1) and extra pwn in scr 
Please just need the amx of the main file 
I already read all the instructions and am going to try compiling again
