### ISSUE TITLE
Help needed 🙏🙏

### ISSUE THREAD

**Issue by chuksthemodder** [WoutProvost/FCNPC-Boss#24]
![Screenshot_20230511-232002](https://github.com/WoutProvost/FCNPC-AI/assets/132638145/5e84eda9-fbd6-49dd-ba71-15479be36c7d)

This is what I get when trying to complie the filterscripts 
Please I really need this

**Comment by WoutProvost** [comment]
OK, I see. I've quickly made a new release that brings the include and examples up to date with the latest versions of FCNPC and the compiler: [FCNPC-AI 1.1.2](https://github.com/WoutProvost/FCNPC-AI/releases/tag/v1.1.2)
